# .github/workflows/build.yml
name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-pc-windows-gnu
          override: true

      - name: Install mingw-w64
        run: sudo apt-get update && sudo apt-get install -y mingw-w64

      - name: Build
        run: cargo build --release --target x86_64-pc-windows-gnu

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: filefix-hunter-windows
          path: target/x86_64-pc-windows-gnu/release/filefix-hunter.exe
